name: Yamu Car Rental - Local
values:
  - key: baseUrl
    value: 'http://localhost:5000'
    enabled: true
    type: default
  - key: token
    value: ''
    enabled: true
    type: default
  - key: vehicleId
    value: ''
    enabled: true
    type: default
  - key: driverAdId
    value: ''
    enabled: true
    type: default
  - key: bookingId
    value: ''
    enabled: true
    type: default
  - key: userId
    value: ''
    enabled: true
    type: default
  - key: roleKey
    value: driver
    enabled: true
    type: default
  - key: notificationId
    value: ''
    enabled: true
    type: default
