import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { Car, Clipboard, Check, ArrowLeft, Smartphone, Share2 } from 'lucide-react';
import { toast } from 'react-toastify';
import API from '../services/api';

const VehicleDetails = () => {
    const { id } = useParams();
    const [vehicle, setVehicle] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const [copied, setCopied] = useState(false);

    useEffect(() => {
        const fetchDetails = async () => {
            try {
                setLoading(true);
                const response = await API.get(`/vehicles/${id}`);
                setVehicle(response.data);
            } catch (err) {
                console.error("Error fetching details:", err);
                setError("Vehicle not found.");
            } finally {
                setLoading(false);
            }
        };

        if (id) fetchDetails();
    }, [id]);

    const copyToClipboard = () => {
        if (!vehicle) return;
        
        const detailsText = `
--- VEHICLE INFO SHEET ---
REG NO: ${vehicle._id}
VEHICLE: ${vehicle.brand} ${vehicle.model}
YEAR: ${vehicle.year}
FUEL: ${vehicle.fuel}
TRANS: ${vehicle.transmission}
SEATS: ${vehicle.seats}
MILEAGE: ${vehicle.distance} Km
PRICE: Rs. ${vehicle.pricePerDay} /Day
STATUS: ${vehicle.availability}
OWNER: ${vehicle.owner}
PHONE: ${vehicle.phone}
--------------------------
Generated by YAMU System`;

        navigator.clipboard.writeText(detailsText.trim());
        setCopied(true);
        toast.success("Text copied for Notepad!");
        setTimeout(() => setCopied(false), 2000);
    };

    if (loading) return <div className="p-10 text-center text-slate-400 font-bold uppercase tracking-widest animate-pulse">Scanning...</div>;
    if (error || !vehicle) return <div className="p-10 text-center text-red-500 font-bold bg-white m-6 rounded-2xl shadow-lg border border-red-50">System Error: {error}</div>;

    const DataRow = ({ label, value, isLast = false }) => (
        <div className={`py-4 flex justify-between items-center ${!isLast ? 'border-b border-slate-100 border-dashed' : ''}`}>
            <span className="text-[10px] text-slate-400 font-black uppercase tracking-widest">{label}</span>
            <span className="font-mono font-black text-slate-800 text-sm tracking-tight">{value || 'N/A'}</span>
        </div>
    );

    return (
        <div className="min-h-screen bg-[#FDFDFD] pb-12 font-sans px-4">
            <div className="max-w-md mx-auto pt-8">
                
                <div className="flex items-center justify-between mb-8">
                    <button onClick={() => window.history.back()} className="w-10 h-10 flex items-center justify-center bg-white border border-slate-100 rounded-xl shadow-sm text-slate-400">
                        <ArrowLeft size={18} />
                    </button>
                    <div className="text-center">
                        <h2 className="text-xs font-black text-slate-300 uppercase tracking-[0.3em]">Vehicle Sheet</h2>
                        <p className="text-slate-900 font-black text-lg -mt-1 tracking-tighter uppercase">{vehicle._id}</p>
                    </div>
                    <button onClick={copyToClipboard} className={`w-10 h-10 flex items-center justify-center rounded-xl shadow-sm transition-all ${copied ? 'bg-green-500 text-white' : 'bg-blue-600 text-white'}`}>
                        {copied ? <Check size={18} /> : <Clipboard size={18} />}
                    </button>
                </div>

                {/* The "Note Pad" UI */}
                <div className="bg-white rounded-[2rem] shadow-2xl shadow-slate-200/50 border border-slate-100 overflow-hidden relative">
                    <div className="h-2 bg-blue-600 w-full mb-2"></div>
                    <div className="p-8">
                        <div className="flex justify-center mb-8">
                            <div className="w-full h-40 bg-slate-50 rounded-2xl overflow-hidden border border-slate-100 flex items-center justify-center">
                                {vehicle.imgUrl ? (
                                    <img src={vehicle.imgUrl} alt="car" className="w-full h-full object-cover" />
                                ) : (
                                    <Car className="text-slate-200" size={64} />
                                ) }
                            </div>
                        </div>

                        <div className="space-y-0 text-sm">
                            <DataRow label="Manufacturer" value={vehicle.brand} />
                            <DataRow label="Model Series" value={vehicle.model} />
                            <DataRow label="Manufacture Year" value={vehicle.year} />
                            <DataRow label="Propulsion" value={vehicle.fuel} />
                            <DataRow label="Transmission" value={vehicle.transmission} />
                            <DataRow label="Total Seats" value={vehicle.seats || 5} />
                            <DataRow label="Current Odometer" value={`${vehicle.distance?.toLocaleString()} Km`} />
                            <DataRow label="Status/Health" value={vehicle.availability} />
                            <DataRow label="Daily Rate (LKR)" value={`Rs. ${vehicle.pricePerDay?.toLocaleString()}`} isLast={true} />
                        </div>
                    </div>
                </div>

                <div className="mt-6 bg-blue-50 rounded-2xl p-6 border border-blue-100">
                    <div className="flex items-center justify-between">
                        <div>
                            <p className="text-[10px] text-blue-400 font-black uppercase tracking-widest leading-none mb-1">Owner Primary Contact</p>
                            <p className="font-black text-blue-900 text-lg">{vehicle.owner}</p>
                            <p className="font-mono text-blue-600 font-bold">{vehicle.phone}</p>
                        </div>
                        <a href={`tel:${vehicle.phone}`} className="w-12 h-12 bg-blue-600 rounded-2xl flex items-center justify-center text-white shadow-lg shadow-blue-100">
                            <Smartphone size={20} />
                        </a>
                    </div>
                </div>

                <div className="mt-8 text-center bg-slate-50 p-4 rounded-2xl border border-dashed border-slate-200">
                    <p className="text-[10px] text-slate-400 font-black uppercase tracking-[0.2em] mb-3">Copy details for internal notes</p>
                    <button 
                        onClick={copyToClipboard}
                        className="flex items-center gap-2 mx-auto bg-white border border-slate-100 px-4 py-2 rounded-xl text-blue-600 font-black text-[10px] uppercase tracking-widest shadow-sm hover:shadow-md transition-shadow"
                    >
                        <Share2 size={12} /> Share Info Block
                    </button>
                </div>
            </div>
        </div>
    );
};

export default VehicleDetails;
